### ISSUE TITLE
Is DialogRoot deprecated?

### ISSUE THREAD

**Issue by jrajav** [jamesmfriedman/rmwc#109]
### What RMWC Version are you using?

1.0.0

### What browser(s) and React Version is this bug affecting?

Chrome 63.0.3239.132

### What build system are you using?

Webpack

### What are the steps to reproduce the bug?

Write an old-style Dialog usage, e.g.:

```jsx
<Dialog
  open={ addPlaylistOpen }
  onClose={ handleAddPlaylistClose }
>
  <DialogRoot>
    <DialogSurface>
      <DialogBody>
        <TextField
          placeholder={ t( 'userPlaylists-addPlaceholder' ) }
          value={ addPlaylistInput }
          onChange={ handleChangeAddPlaylistInput }
        />
      </DialogBody>
      <DialogFooter>
        <DialogFooterButton cancel>{ t( 'userPlaylists-addCancel' ) }</DialogFooterButton>
        <DialogFooterButton accept onClick={ handleAddPlaylistConfirm }>
          { t( 'userPlaylists-addConfirm' ) }
        </DialogFooterButton>
      </DialogFooter>
    </DialogSurface>
    <DialogBackdrop />
  </DialogRoot>
</Dialog>
```

### What is the expected behavior?

Dialog properly displays when set to `open={ true }`.

### What is the actual behavior?

Dialog does not properly display.

### Any other information you believe would be useful?

This appears to be because the Dialog component now exposes the same sort of element and MDC class name that DialogRoot used to, however the Dialog component is the only one that receives the "open" classname upon dialog open that sets `visibility: visible`. This results in the Dialog remaining invisible because the DialogRoot component still has `visibility: hidden`. Is the usage of DialogRoot deprecated? It isn't used in the current docs, so it might seem so - however, it is still exported as a component in the library itself.

**Comment by jrajav** [comment]
Note - simply removing DialogRoot in the above example makes it work as expected.

**Comment by j-o-d-o** [comment]
In your example, you would have two times the <aside/> element since <Dialog/> returns a <DialogRoot/>. I guess this is to have the structure as close as possible to the original MDC structure. 
Basically what changed is that now the Dialog Component returns a DialogRoot whereas before, the child element was used, which had to be DialogRoot. So I wouldn't say it is deprecated, it is just used in a different way.

I would leave the DialogRoot export thou. Maybe someone wants to implement their own Dialog wrapper, then it is convenient to have.

**Comment by jamesmfriedman** [comment]
@jrajav it's not deprecated, it's just a change in structure.

Before V1, the design of the Dialog in RMWC was a bit of an anti-pattern. It was basically a controller component that returned a default template instead of being fully composable

After V1, The Dialog component returns the DialogRoot and nothing else. Its up to you to fill it with the rest of the Dialog contents. SimpleDialog was created which implements the entire Dialog template.

Simple answer, you don't need to use DialogRoot for anything. It exists in the event you ever want to build a Dialog without the actual functionality.
