### ISSUE TITLE
Text as List metadata

### ISSUE THREAD

**Issue by nilsga** [jamesmfriedman/rmwc#162]
According to the demo at https://material-components-web.appspot.com/list.html, it should be possible to use text as List metadata. RMWC on the other hand, seems to only support icons as metadata.

**Comment by jamesmfriedman** [comment]
Thanks for reporting this, I'll get it resolved for the next release

**Comment by jamesmfriedman** [comment]
This was an odd place in the material api where they are using one item for multiple purposes. I found a workaround and added it to the docs.

```
<ListItem>
    <ListItemGraphic>mood</ListItemGraphic>
    <ListItemText>Icecream</ListItemText>
    <ListItemMeta tag="span" basename="">Text!</ListItemMeta>
  </ListItem>
````

That tag is only necessary because icons are `'<i>` elements by default. I would change this to fix this issue but I'm afraid that might cause issues for other people.

Will be updated in the docs for the next release.
