### ISSUE TITLE
Importing modules from @material vs. distributed files

### ISSUE THREAD

**Issue by rjdestigter** [jamesmfriedman/rmwc#232]
### What RMWC Version are you using?

`1.6.3`

### What build system are you using?

> Webpack `4.8.3`

### What are the steps to reproduce the bug?

This may be on your radar already but I couldn't find an existing issue or documentation. Some of the components provided by `material-components-web`  provide a main entry point besides a distributed version that can be tree-shaken by Webpack.

I noticed that not all `@material` components are packaged this way yet.

### What is the expected behavior?

For example, instead of importing from
```
import { MDCCheckbox } from '@material/checkbox/dist/mdc.checkbox';
```
you can now import
```
import { MDCCheckbox } from '@material/checkbox';
```

### What is the actual behavior?
RMWC components are explicitly importing distributed components of  `@material` packages.

### Any other information you believe would be useful?

Currently I am using `resolve.alias` to configure Webpack to pick up on any "tree-shake-able" `@material` components.

```
webpackConfig.resolve.alias = {
      '@material/base/dist/mdc.base': project.paths.packages('@material/base/index.js'),
      '@material/dialog/dist/mdc.dialog': project.paths.packages('@material/dialog/index.js'),
      '@material/drawer/dist/mdc.drawer': project.paths.packages('@material/drawer/index.js'),
      '@material/form/dist/mdc.formField': project.paths.packages('@material/form-field/index.js'),
      '@material/icon/dist/mdc.iconToggle': project.paths.packages('@material/icon-toggle/index.js'),
      '@material/menu/dist/mdc.menu': project.paths.packages('@material/menu/index.js'),
      '@material/radio/dist/mdc.radio': project.paths.packages('@material/radio/index.js'),
      '@material/ripple/dist/mdc.ripple': project.paths.packages('@material/ripple/index.js'),
      '@material/slider/dist/mdc.slider': project.paths.packages('@material/slider/index.js'),
      '@material/toolbar/dist/mdc.toolbar': project.paths.packages('@material/toolbar/index.js'),
      '@material/textfield/dist/mdc.textfield': project.paths.packages('@material/textfield/index.js'),
      '@material/tabs/dist/mdc.tabs': project.paths.packages('@material/tabs/index.js'),
      '@material/checkbox/dist/mdc.checkbox': project.paths.packages('@material/checkbox/index.js'),
}
```

It decreased the unparsed build size of `@material` from `1.3Mb` to `605Kb`

**Comment by jamesmfriedman** [comment]
I’m glad you found a workaround for your tree shaking needs. 

The reason RMWC includes the dist files is because the regular material modules are es6 and will break builds and browsers unless people explicitly include them via their Babel configuration (which is off by default for things like create react app). 

Happy to talk about a workaround but es5 compatible distributions are still the safest bet for the masses.

**Comment by rjdestigter** [comment]
Yeah, you'd have to adjust the rmwc build script to create 2 versions. My guess is one where `package.json/main` points to the version using the dist version of @material packages and one where `package.json/jsnext:main` maybe points to the es6 imported version?

If you would like to have that I could take a look at this. I tend to avoid `jsnext:main` though in my projects and tick to either `main` or `module`

**Comment by jamesmfriedman** [comment]
This will be partially fixed in 5.x.x. I've been talking to some people on the material team and they're possibly instrumenting some of the things that would be needed to make this happen.

- RMWC will now have dist/* and next* modules that are released along side of the original Typescript Source
- next/* will include the TS declarations as well as ES5 compatible code, but in es module format (this seems to be the running recommendation for the best interop.
- The `modules` key will be declared in each individual components package.json.
- There are open issues with MDC to follow the same pattern. Once both are implemented, you should be able to enjoy a much smaller build.

**Comment by jamesmfriedman** [comment]
- RMWC now supports "sideEffects: false" and "modules" keys in package.json for tree shaking
- I've worked with the maintainers of MatWeb to include the same
- All of the imports in RMWC should support MDC when they release their next / modules format
- Your bundle will be smaller now with RMWC, and even smaller when MDC supports it.
