### ISSUE TITLE
Changing a TextField type between box/outlined/normal causes rendering issues

### ISSUE THREAD

**Issue by rboei** [jamesmfriedman/rmwc#233]
### What RMWC Version are you using?
    "rmwc": "^1.6.2",
react: 16.3.2

### What browser(s) and React Version is this bug affecting?
Firefox, latest

### What build system are you using?

webpack
### What are the steps to reproduce the bug?

https://codesandbox.io/s/pymm1l7ljm

### What is the expected behavior?
The box rerenders itself with the new style and keeps functioning

### What is the actual behavior?
It rerenders, but its not working entirely correct.E.g. change from box to outlined and the rendering on input focus does not remove the border for the label, or change from outline to box -> The label doesnt move anymore.

**Comment by jamesmfriedman** [comment]
This is a known issue that I haven’t tried to work around because I doesn’t seem like a common use case. Outlined and normal text fields have slightly different code paths MDC ans requires the text field to know it is outlined at init time. 

One thing you can try is using the key prop and changing it to a different value the textfeld switches to outlined. This should cause react to throw away the component and initialize a new one.

**Comment by rboei** [comment]
Changing the key did help - i should have thought about that myself oO - Thank you :)
