### ISSUE TITLE
Bundle size reported as 88.7 kB (min+gzipped)

### ISSUE THREAD

**Issue by mrchief** [jamesmfriedman/rmwc#240]
According to docs, RMWC is around 15KB

![image](https://user-images.githubusercontent.com/781818/40892263-a59c7404-6762-11e8-8b33-b67cd3f72ea6.png)

According to [bundlephobia](https://bundlephobia.com/result?p=rmwc@1.6.4), it's close to 90Kb (min + gzipped)

![image](https://user-images.githubusercontent.com/781818/40892268-bbac8e6e-6762-11e8-991d-095f70882dbb.png)

Is bundlephobia including  entire material-components-web package? Or is there some other discrepancy?

**Comment by jamesmfriedman** [comment]
Hi @mrchief! There was a time where that was an accurate statement, but MDC as well as RMWC have grown a lot since then. I'm definitely interested in getting the size back down, so how about we turn this issue into a couple of things:

- [ ] Updates docs to reflect actual build size
- [ ] Look for optimizations to decrease the build size

**Comment by jamesmfriedman** [comment]
Reporting back on this

Bundlephobia added a composition tool which exposes what really makes up the package.The 90K minified includes the code coming from MDC.

RMWC only accounts for 19% of that number. Mix that in with tree shaking and your apps should be nice and lean.

![image](https://user-images.githubusercontent.com/975256/42949518-e93fc930-8b3f-11e8-87f5-df62a664219c.png)
