### ISSUE TITLE
Explore fluid syntax

### ISSUE THREAD

**Issue by jamesmfriedman** [jamesmfriedman/rmwc#258]
Look into exploring a fluid syntax based on default exports.

Current Example
```
import {
  Card,
  CardPrimaryAction,
  CardMedia,
  CardAction,
  CardActions,
  CardActionButtons,
  CardActionIcons
} from 'rmwc/Card';

<Card>
  <CardPrimaryAction>
    <CardMedia/>
  </CardPrimaryAction>
  <CardActions>
    <CardActionButtons>
      <CardAction>Read</CardAction>
      <CardAction>Bookmark</CardAction>
    </CardActionButtons>
    <CardActionIcons>
      <CardAction/>
      <CardAction icon use="share" />
      <CardAction icon use="more_vert" />
    </CardActionIcons>
  </CardActions>
</Card>
```

Proposed, keep the current syntax and add this in addition when using the default import.
```
import Card from 'rmwc/Card';

<Card>
  <Card.PrimaryAction>
    <Card.Media/>
  </Card.PrimaryAction>
  <Card.Actions>
    <Card.ActionButtons>
      <Card.Action>Read</Card.Action>
      <Card.Action>Bookmark</Card.Action>
    </Card.ActionButtons>
    <Card.ActionIcons>
      <Card.Action/>
      <Card.Action icon use="share" />
      <Card.Action icon use="more_vert" />
    </Card.ActionIcons>
  </Card.Actions>
</Card>
```

**Comment by mutsys** [comment]
I'm kind of iffy about this proposed enhancement due to the impact it could have on the final size of bundles produced via `webpack` w.r.t. code-splitting and lazy-loading. Overly clever "convenience" exports/imports as described above typically have the undesirable side effect of inflating bundle size by forcefully including every "sub-export" of `Card` in the final bundle whether or not it is actually used in the component that imports it. Default exports as described in this proposal come with a disproportionately large penalty compared to the amount of typing it may save you (which is probably better handled in your editor/ide with plugins that assist with selecting imports).

A similar issue already exists with the `RMWCProvider` component. Due to some sub-optimal module definition and exports/imports, using `RMWCProvider` will forcefully include all of the `Ripple` module (as well as a bunch of other unrelated components from `Base`) in the bundle whether or not you import the `Ripple` component itself.

As one of the stated goals of `rmwc` is to be "lean and mean", I would think that anything that serves to increase the size of bundles intended for production usage should be avoided at all costs.

**Comment by jamesmfriedman** [comment]
I completely agree and that’s exactly the piece I wanted to explore. I think I’ll avoid it anyways in favor of keeping a single way of doing things. Also people could always do `import * as Card from ‘rmwc/Card’ which would be roughly equivalent, albeit with some verbose names like Card.CardAction. 

Thanks for all of your recent feedback. You’ve been very helpful. I’ll be digging into your typescript PR sometime this weekend.
