### ISSUE TITLE
Select does not use defaultValue

### ISSUE THREAD

**Issue by ClashTheBunny** [jamesmfriedman/rmwc#259]
## RMWC or MDC?

Possibly RMWC

### What RMWC Version are you using?

yarn.lock:
```
rmwc@^1.7.3:
  version "1.7.3"
  resolved "https://registry.yarnpkg.com/rmwc/-/rmwc-1.7.3.tgz#9fd6785a5d5d261862b7b1540cda947f320162c6"
  dependencies:
    classnames "^2.2.5"
    hyperform "^0.9.9"
    material-components-web "0.36.1"
    mutation-observer "^1.0.3"
    prop-types "^15.6.1"
```

### What browser(s) and React Version is this bug affecting?

Firefox 61.0 and Chrome Version 67.0.3396.87 (Official Build) (64-bit)

### What build system are you using?

shadow-cljs

### What are the steps to reproduce the bug?

Add data to the item's defaultValue, inspect in both the dom and in React Dev Tools, both show:
```
Props
defaultValue: "US"
label: "Country"
onChange: fn()
options: Array[248]
placeholder: ""
```

### What is the expected behavior?

It should select that item in the options as the selected item.

### What is the actual behavior?

Shows up as blank.

### Any other information you believe would be useful?
 I've tried many different ways of getting the component reactive.  If I set the value, I can't change the displayed value, although the underlying variable does change.

**Comment by jamesmfriedman** [comment]
Thanks for reporting this, I'll look into it.

If you get a chance to post a short repro in the code sandbox that would be really helpful.

**Comment by ClashTheBunny** [comment]
I've never done jsx, but I think this is what you're looking for:
https://codesandbox.io/s/344mw47mvq

**Comment by Deilv** [comment]
The example you posted seems to be working as intended (can’t reproduce). Have you tried using the latest version of rmwc?

**Comment by ClashTheBunny** [comment]
It feels like this isn't what should happen.  Once set, it doesn't change.

Randall Mason
randall@mason.ch

**Comment by Deilv** [comment]
Ok, I see what the problem is.
First of all defaultValue is not defined in the API of either RMWC or MWC, so it's ignored.
In order to achieve this behavior you specified
```
value = {props.value}
```
which makes it controlled component and does indeed select your value.

However, bi-directional binding doesn't work in React.
In order to achieve the desired behavior you have two options:
1. Set the value that you want as default first in the options array.
2. Implement internal state and use onChange to update it when a selection is made.

Here is an example that works (using the 2nd option):
https://codesandbox.io/s/w6po5yvy77

**Comment by ClashTheBunny** [comment]
Thanks!  I'll dig into this.

**Comment by Deilv** [comment]
@jamesmfriedman I actually have a use case that relies on defaultValue, which makes me wonder, why Select doesn't support it? Textfield does. Is it an oversight? The only reference I could find was a line which is setting it to undefined if value is defined, '' otherwise. It should be fairly easy to implement.

**Comment by deilv** [comment]
@wildeyes did you just comment on a year old closed issue?

**Comment by aktary** [comment]
It is [in the docs](https://rmwc.io/select-menus) and as far as I can tell, doesn't work.  Since `enhanced` doesn't allow for use of `inputRef`, I can't rely on the React-Hook-Form library to manage this for me, so am having to do so manually. Having a working `defaultValue` would be a convenient way, but I can make it work by hand.
