### ISSUE TITLE
slider does not function with a hidden element

### ISSUE THREAD

**Issue by akonsowski** [jamesmfriedman/rmwc#279]
### What RMWC Version are you using?

> 1.6.4

### What browser(s) and React Version is this bug affecting?

> Google Chrome Version 67.0.3396.99 (Official Build) (64-bit)

### What build system are you using?

>Create React App

### What are the steps to reproduce the bug?

put a slider in a hidden div,grid...etc when the hidden element is shown the slider does not function and automatically goes to the max value

 https://codesandbox.io/s/p3ynorjm7

### What is the expected behavior?

> when the element is unhidden the slider should function normally

### What is the actual behavior?

the slider is not interactive and is unable to change the value of the state.

**Comment by jamesmfriedman** [comment]
This is an issue with MDC.

- The slider has an "on layout" function that gets called. By default, MDC has one bound to the window.onResize. event.
- Workaround #1. Trigger a window resize event manually after you show the slider
- Workaround #2. Instead of hiding it, just don't render it at all. This will make React render a new one when it becomes visible, avoiding your problem
- Workaround #3. Use opacity instead of hidden
- Workaround #4. Add a key prop to the element that changes when its visible vs hidden. This will alos cause React to render it when it changes.

**Comment by akonsowski** [comment]
thanks for the quick response @jamesmfriedman.  I just implemented the 1st work around and it is functioning as intended now.
