### ISSUE TITLE
Controlled Checkbox is unresponsive in iOS

### ISSUE THREAD

**Issue by vasco3** [jamesmfriedman/rmwc#294]
## RMWC or MDC?

* unsure

### What RMWC Version are you using?

v1.9.2

### What browser(s) and React Version is this bug affecting?

* iPhone Safari
* iPhone Brave

### What build system are you using?

* nextjs (webpack)

### What are the steps to reproduce the bug?

```jsx
 <Checkbox 
    onChange={handleChange} 
    checked={values.sunday}
    name="sunday"
    label="Sunday"
 />
```

Even the [rmwc doc](https://jamesmfriedman.github.io/rmwc/checkboxes) page has the same issue

### What is the expected behavior?

The checkbox should change the checked state when clicked or tapped.

### What is the actual behavior?

The checkbox remains unchecked

**Comment by jamesmfriedman** [comment]
This will be fixed in a patch today.

I wish I had a good reason why this was happening but I don't. Wrapping the change handler internally with a RAF fixes the issue on iOS and doesn't appear to impact the behavior in any other browser.
 
My gut tells me this has something to do with nuances in handling between click and touch events.

**Comment by vasco3** [comment]
Thanks James!
btw, this is an awesome project

**Comment by jamesmfriedman** [comment]
Thanks @vasco3. Spread the love, spread the word ;)
