### ISSUE TITLE
TopAppBar fixed option issue.

### ISSUE THREAD

**Issue by Jromero97** [jamesmfriedman/rmwc#326]
Hi, I have an issue or could be just bad implementation by my part, I'm using <TopAppBar/> Component but when I use 'fixed' property nothing happens, some advice to solve this?

My imports are this:

` import {TopAppBar, TopAppBarRow, TopAppBarSection, TopAppBarNavigationIcon, TopAppBarTitle} from '@rmwc/topappbar';` when I'm trying to use `'@rmwc/top-app-bar'` I get 'Module not found' from webpack.

My code is the following:

`<TopAppBar fixed>
     <TopAppBarRow>
          <TopAppBarSection alignStart>
                <TopAppBarNavigationIcon icon='menu'>
                </TopAppBarNavigationIcon>
                <TopAppBarTitle> My Title </TopAppBarTitle>
          </TopAppBarSection>
     </TopAppBarRow>
</TopAppBar>`

**Comment by jamesmfriedman** [comment]
What version do you have installed. Also have you tried using the code sandbox to make a repro? That’s the easiest way to check to see if it’s a configuration issue. Also have you included the styles?

**Comment by Jromero97** [comment]
I have version 2.2.3, and I'm trying with the first with the `<Toolbar/>` component and it works but when I try with `<TopAppBar/>` and It doesn't, I have the styles imported.

**Comment by jamesmfriedman** [comment]
Right. The docs use the top app bar as fixed. Can you try to make a reproduction of your issue using rob code sandbox?

**Comment by Jromero97** [comment]
I'll try and send the link just wait

**Comment by Jromero97** [comment]
This is the link of my sandbox to show what's my issue.

When I try to get a 'fixed' TopAppBar

[Sandbox](https://codesandbox.io/s/km5lll99or)

**Comment by j-o-d-o** [comment]
Thx for the Sandbox. Works on my machine ; ) 
What is the exact issue you are seeing? Does it not show up at all, or is some behaviour not as expected?

**Comment by Jromero97** [comment]
The behaviour that I expect is a TopAppBar full-width fixed to the top, but on my laptop when I set 'fixed' nothing happens

**Comment by jamesmfriedman** [comment]
We'd love to help @Jromero97 but there is nothing wrong with the code or the sandbox you sent.

Here is a slightly modified sandbox that shows the app bar working as intended. It worked before I made the changes, this just better illustrates how to use it.

https://codesandbox.io/s/1zjr7o85r3

- I updated the imports. I think you have some configuration error on your machine because the package is called @rmwc/top-app-bar
- I put an element in the body that is tall enough to allow you to scroll, you can clearly see the app bar being fixed to the top
- You still have to position the top app bar. The body simply had a margin on it that was pushing the app bar over
- You were missing the icon font, I added it
- I added TopAppFixedBarAdjust to push the content down below the bar.

**Comment by Jromero97** [comment]
Oh, Thx a lot, that was the margin problem, I couldn't see before, your library it's pretty good and useful, I'm newbie with React but I'm trying to learn fast.
