### ISSUE TITLE
Shape implementation is not compatable with transparent/image backgrounds

### ISSUE THREAD

**Issue by Wroud** [jamesmfriedman/rmwc#329]
I'm not shure is it RMWC or MDC issue,
Also incorrect when use "text-align: center;"
https://codesandbox.io/s/ov9nvjr33y

**Comment by jamesmfriedman** [comment]
Bad news, the shape api has been deprecated by mdc and will be removed in the next release. It was a novel idea but turned out to be too hard to implement in css and html. They have a new api that is sass based and supports rounding of corners. 

If you want the angled corners I’d suggest using custom svgs or css clip path.

**Comment by Wroud** [comment]
Bad to hear it, thx for reply i missed it in mdc docs
