### ISSUE TITLE
Datatables pagination

### ISSUE THREAD

**Issue by Jromero97** [jamesmfriedman/rmwc#357]
Hey, I have a doubt with the datatable component of rmwc, there is a function to make pagination like datatable.js plugin? or any related?

**Comment by jamesmfriedman** [comment]
There isn’t one built in, but the way it is structured is intentional so it can easily be used with third party libraries like react-virtualized.

**Comment by jamesmfriedman** [comment]
@Jromero97 I'm going to close this one out since its not an issue. I don't plan on adding pagination to the data table component since data handling can be quite specific to how your app is structured. Let me know if there is something else I can help with.

**Comment by windgaucho** [comment]
@jamesmfriedman Can you please show me an example on how can I use the Datatables component with react-virtualized?

**Comment by jamesmfriedman** [comment]
I need to update the docs to not call that out. I wrongfully assumed it would work but unfortunately react virtualized doesn’t handle anything except divs. 

I’ll put on the todo list finding a virtual scrolling library that plays nice.

**Comment by windgaucho** [comment]
About pagination? have you used some pagination component with the datatables component?

**Comment by jamesmfriedman** [comment]
Just home rolled ones. The whole thing is very dependent on any particular app's state and if want to paginate via page numbers or scrolling. Curious, how much data are you trying to visualize?

**Comment by windgaucho** [comment]
It's depends, I want to use the datatable in every component of my app. In some components (components that handle the configuration of my app) it is not much data.
But in other component (the main ones) handle to much data.
Nevertheless I want to use the same datatable component in all my app and keep my ui consistent.
Currently I am using antd in all of my applications and I want to migrate it to material component but I am unnable to find some datatable component that suits my needs.
Because of that I am asking if you know some paginator that you have used with your datatable component.

**Comment by ohanar** [comment]
Is there any update on this? I'm also interested in this for lists. For reference, I have tables and lists that can have more than a million rows, which crashes browsers unless something like react-virtualized or react-window is used.

**Comment by jamesmfriedman** [comment]
Yes as a matter of fact, I was able to solve it with react-window.

https://github.com/bvaughn/react-window/issues/60#issuecomment-588397239
