### ISSUE TITLE
TypeScript error (missing context prop)

### ISSUE THREAD

**Issue by garth** [jamesmfriedman/rmwc#372]
# Bug Description

The TabBar and TopAppBar are currently casing the following typescript errors:

# Error Messages

```
[ts]
JSX element type 'TabBar' is not a constructor function for JSX elements.
  Property 'context' is missing in type 'TabBar'. [2605]
```

```
[ts]
JSX element type 'TopAppBar' is not a constructor function for JSX elements.
  Property 'context' is missing in type 'TopAppBar'. [2605]
```

## Versions

typescript@3.1.6
rmwc@3.0.10

**Comment by jamesmfriedman** [comment]
This is definitely new as of the last couple of weeks. See this issue https://github.com/DefinitelyTyped/DefinitelyTyped/commit/9039892f8ea3823b0a37d2b9764ba413a9eb6aa9#commitcomment-31247157

Any suggestions on this? The guidance seems to just be to declare context as any on all of the components.

**Comment by jamesmfriedman** [comment]
A couple of things in the meantime
- Looks like 1 option would be for you to downgrade to the previous version of @types/react if possible since this is a new breaking change.
- Another option would be to declare `context:any` on any React.Component in your own types directory. You might be able to do this by extending the interface, just an idea.

**Comment by jamesmfriedman** [comment]
Fixed with the release of V5
