### ISSUE TITLE
Missing props to control should the dialog close if click outside

### ISSUE THREAD

**Issue by phmngocnghia** [jamesmfriedman/rmwc#376]
- What RMWC Version are you using [major.minor.patch]: Lastest
- Name your build system [Webpack, Rollup...]: Webpack

- Describe the bug with as much detail as possible:
* There is no props to control should the dialog close if i click outside the dialog. eg: closeIfClickOutSide or something and it's really anoyying.

- What happened, and what was supposed to happen:
* There is no props to control should the dialog close if i click outside

**Comment by jamesmfriedman** [comment]
Hi @PhmNgocNghia 

You can actually just keep the `open` prop set to true and the Dialog will not close.

https://codesandbox.io/s/wwvr491qwl

**Comment by jamesmfriedman** [comment]
Did that resolve your issue?

**Comment by nguyenkevtran** [comment]
@jamesmfriedman I think your suggested way does not actually resolve the issue. 

As you can also see in the example you provided, the screen kinda "flashes" when user clicks outside dialog. I'm not sure about the under-the-hood behavior here but I guess the reason is that the `closing` event is still triggered, causing the dialog and its backdrop to hide. Then the dialog checks for the `open` prop, which is still true, and displays itself again.

I agree with @PhmNgocNghia that the real solution here is a prop to prevent the `close` event when user clicks outside of dialog a.k.a the backdrop.

**Comment by jamesmfriedman** [comment]
That behavior is instrumented by MDC under the hood. I can make sure the open prop is respected and that it does not try to close the dialog.

**Comment by nguyenkevtran** [comment]
@PhmNgocNghia I found a workaround in material-components/material-components-web#2380

**Comment by jamesmfriedman** [comment]
Available in the 5.2.0-alpha.0
