### ISSUE TITLE
Suggestion: Data Table Sorting Arrow position

### ISSUE THREAD

**Issue by Deilv** [jamesmfriedman/rmwc#392]
This isn't an issue, but a functional and cosmetic suggestion regarding the Data Table element.

I'd like to suggest that the sorting arrow is placed on the right because that's where it's expected to be in most other software.

As it is now (on the left) it renders an empty space prepending the cell content when sortDir=null.

Perhaps this could be placed on the left when alignEnd is selected, or maybe a control can be added to define where the arrow is placed.

An alternative would be to export the DataTableSortIcon with a direction prop to allow us to manually display it in the table cell.

**Comment by jamesmfriedman** [comment]
Hi @Deilv thanks for reporting this! For the most part, RMWC strives to implement the material spec as closely as possible which is why the sort icons are placed on the left.

This is really easy to override though with a little bit of custom CSS. RMWC uses BEM syntax, so you can either select the column directly, or you could wrap it in your own styles if you're using styled components or anything else like that.

https://codesandbox.io/s/mmj4zrp37x
