### ISSUE TITLE
TextField elementRef crash

### ISSUE THREAD

**Issue by robcaldecottvelo** [jamesmfriedman/rmwc#395]
RMWC 4.0.6

Using `elementRef` in a `TextField` will cause an MDC crash as soon as the field gets focus.

Here is an example:

https://codesandbox.io/s/l2myp9lkqm

Open Chrome DevTools and click on the text field. Remove the `elementRef` prop and the issue goes away.

```js
class App extends React.Component {
  state = { value: "" };

  input = React.createRef();

  render() {
    return (
      <TextField
        label="Test"
        value={this.state.value}
        elementRef={this.input}
        onChange={evt => {
          this.setState({ value: evt.target.value });
        }}
      />
    );
  }
}
```

**Comment by jamesmfriedman** [comment]
What are you using elementRef for in this particular case? I know the issue, it’s  come up during the TS refactor as well.

**Comment by robcaldecottvelo** [comment]
We want to customise the validation so intend on calling `setCustomValidity` on the `<input>`. We can work around this for now using a `ref` and `foundation_.adapter_.getNativeInput()`.

(we have a phone number component and are validating the number using `libphonenumber-js`. We use a combination of the `TextField` `invalid` prop and `setCustomValidity` to ensure forms can not be submitted with invalid phone numbers. Once you want to validate using something other than a `pattern` it starts to get messy.)

**Comment by jamesmfriedman** [comment]
This particular issue suffers from a control flow problem that has existed for a while...
- React 15.X - 16.2 didn't have the concept of Ref forwarding. elementRef was my own made up version of this
- React 16.3 does forward refs, but now we have an issue. When you put a ref on TextField, does it give you the ref of the Class Component, the root of the textfield component (a div) or the input? I would like feedback on this since I'm working through this exact problem in the 5.X refactor. I don't think the class components should forward their ref since getting a ref to the component itself allows workarounds for tricky issues like the one you are experiencing.
- There is an `inputRef` prop which when looking back through the code should give you what you are looking for. I plan on carrying this over to all form elements since interacting them with manually is a common need.
- elementRef is going away in 5.0 in favor of ref forwarding. Because ref forwarding works differently than passing a normal prop, removal of elementRef will unfortunately be a breaking change.

**Comment by jamesmfriedman** [comment]
Fixed with the release of V5
