### ISSUE TITLE
outlined text field caused overflow

### ISSUE THREAD

**Issue by buncismamen** [jamesmfriedman/rmwc#397]
- What RMWC Version are you using [major.minor.patch]:
4.0.6

- Name your build system [Webpack, Rollup...]:
vanilla create-react-app, webpack 

- Describe the bug with as much detail as possible:
textfield outlined caused overflow when used inside flexbox inside flexbox

- What happened, and what was supposed to happen:
should not overflow

- checkout the sandbox
 https://codesandbox.io/s/n5xwymmz0j

- workaround
using rmwc@next solve the problem 
but damn I'm using typescript so I got typed definition issue
my current workaround is using `overflow: hidden;`

**Comment by jamesmfriedman** [comment]
Related to #380 

This is a very strange bug indeed. A few things:

- This bug is likely caused upstream by material-components-web and is not something that can be easily fixed in RMWC
- In the latest version of material-components-web, they have changed the implementation of the notched outline. 
- Timing wise, RMWC is getting a major upgrade and refactor for the 5.x branch. This is the branch that also happens to include the latest version of material-components-web (0.43.0). The 4.x branch of RMWC will not be receiving this upgrade.
- Thank you for testing out the 5.x branch. I would love to know what the type definition issues you're running into are so I can fix them
- Pending upgrading to 5.x, your workaround is probably the best path forward.

**Comment by jamesmfriedman** [comment]
Fixed with the release of V5
