### ISSUE TITLE
5.x: TextFieldIcon and ChipIcon issues

### ISSUE THREAD

**Issue by robcaldecottvelo** [jamesmfriedman/rmwc#399]
**RMWC 5.0.8-alpha.0**

It looks like `TextFieldIcon` and `ChipIcon` no longer work correctly. See the sandbox here:

https://codesandbox.io/s/vn3o5r8r90

- Icons are displayed in the wrong position
- `TextField` `withLeadingIcon` is not passing `tabIndex` so the icon can not be clicked.

However, I notice that using `Icon` instead of `TextFieldIcon` on the `TextField` examples will render the icons correctly but you still can not click on the leading icon (which we rely on for one of our components.) Changing `ChipIcon` to `Icon` ends up with a large icon.

FWIW we have components that rely on using custom icons plus and we use `data-testid` props on the icons for our automated tests.

Here is the same code using **4.0.6**:

https://codesandbox.io/s/lr3nxp2z9

I also see warnings about deprecated `Icon` props when using custom icon rendering. So if I have this:

```js
<Icon
  icon="gb"
  iconOptions={{
    strategy: "className",
    basename: "flag-icon",
    prefix: "flag-icon-"
  }}
  style={{ height: 24, width: 24 }}
/>
```

I get warnings about `iconOptions` but if I change it to this it will not work:

```js
<Icon
  icon="gb"
  strategy="className"
  basename="flag-icon"
  prefix="flag-icon-"
  style={{ height: 24, width: 24 }}
/>
```

**Comment by jamesmfriedman** [comment]
This is unfortunately (or fortunately depending on how you look at it) one of the few but major breaking changes in the 5.x branch.

- From early on I wanted to support multiple ways of rendering icons because I've encountered them all IRL
- While components are the primary interface in React, passing them around for icons becomes awkward, especially because individual icons have their own identity. TextFieldIcon is subtlety different than ChipIcon, and different than just Icon, even though they all use the Icon component at the base.
- To compound the issue, the icon component itself has grown in complexity, hence the iconOptions. iconOptions has also proved to be an awkward interface because all of the internal api, everytime an icon is used, you have to remember to additionally pass on options.

Because of the above
- All icon props now share the same type signature. They can accept a string, a component, or an icon definition.
- Strings are great for when you are using ligatures, or you have the provider wired up with your customizations
- Components will be passed on to the proper icon, not replace it. Example in the link to follow
- Lastly, you can just pass the spec (basically your props list) as an object.

Examples in the link. I can guarantee this pattern will be stable going forward, but I would definitely love some feedback, especially since you are using it in multiple ways.

https://codesandbox.io/s/88047873n8

**Comment by jamesmfriedman** [comment]
As an addendum, the docs are being updated, just not released on GH yet. You can run the new documentation locally by cloning the typescript branch and running npm i && npm start.

A large amount of release notes will accompany the final release detailing these changes.

**Comment by robcaldecottvelo** [comment]
@jamesmfriedman Fabulous! This is a huge help.
