### ISSUE TITLE
bug on menus on iOS mobile device

### ISSUE THREAD

**Issue by dohomi** [jamesmfriedman/rmwc#419]
Hi
Not sure which one, but I think its `RMWC`. If you open the menu on mobile device (iOS in my case) menus are not closed clicking outside.

Reproduce: just open https://jamesmfriedman.github.io/rmwc/menus on your mobile, the menus open but don't close any more. Only by clicking an item inside the menu-items its closing

I also used `rmwc` for testing and menus are not closing for me on mobile. On desktop it works fine

Cheers

#### UPDATE
The same occurs on `MDC` components and their website. Is there a current workaround? Thats quite a dealbreaker to use menus at the moment

**Comment by jamesmfriedman** [comment]
I agree, this has been quite a pain for me as well and is definitely and MDC bug on their docs site https://material-components.github.io/material-components-web-catalog/#/component/menu

I’d rather get it fixed upstream, I’ll check with the maintainers and see if it’s on their radar. Otherwise it’s long overdue to be fixed!

A workaround for now would be to control the open prop and set it to false manually. Clicking on another clickable element also causes it to close, just not the body on iOS for some reason.

**Comment by dohomi** [comment]
I referenced the issue on their project: https://github.com/material-components/material-components-web/issues/4441
I'd love to use this library in an upcoming project but menus are mandatory to work on all devices. I am wondering how this could slip through Google's radar :-) No offence though I'm just kidding..

**Comment by jamesmfriedman** [comment]
Well, I hope you enjoy using this library and get used to things getting fixed fast ;). 

Publishing 5.1.8 as we speak, was as simple as adding a touchstart listener to the body. Please reopen / report back if there are any additional issues.

**Comment by dohomi** [comment]
@jamesmfriedman nice man! yeah I really start enjoying my journey.. was playing around with material-ui, mwc-react and all the other libs doing material stuff at the moment (I am actually a Vue - guy doing some field work in the React department). The way of theming and your docs were the reason I ended up here keep up the great work 👍

**Comment by jamesmfriedman** [comment]
Great to hear @dohomi :)
