### ISSUE TITLE
add scss files additionally for css components like Avatar to adjust variables

### ISSUE THREAD

**Issue by dohomi** [jamesmfriedman/rmwc#421]
Hi,

it would be nice if this repo would offer similar to mwc a SCSS file additionally to the CSS for being able to overwrite the defaults. Its not a big issue though, but as a mwc user I overwrite all variables in SCSS files and with icons and avatars I would need to take few more steps.

This is definitely the last thing I found, everything else worked 🥇 for me

**Comment by jamesmfriedman** [comment]
RMWC uses all of the standard CSS variables where necessary. These CSS variables will respect the SASS values that get baked in.

As far as the components you have listed above, what customization would SASS being offering thats not currently being respected?

MDC has a VERY complex SASS system built out. One of those goals of this library was to make SASS optional, but happy to know the usecase.

Also, feel free to use Discord for any general questions that aren't necessarily issues. Glad you're enjoying the lib.

**Comment by dohomi** [comment]
@jamesmfriedman I haven't seen the Discord channel in your readme, I'll switch over to that one. I was just thinking of changing icon sizes, they are not set up via vars as far I could see. https://github.com/jamesmfriedman/rmwc/blob/master/src/icon/icon.css

**Comment by jamesmfriedman** [comment]
I don't foresee ever adding support for SASS in this libraries custom components since it would grossly overcomplicate the build and usage.

As far as the actual addon components go, they do use the built in CSS variables and styles where appropriate to fit in with the rest of MDC. In this particular example, icon sizes match the recommended material spec so they fit within all other components.
