### ISSUE TITLE
classNames is not a function

### ISSUE THREAD

**Issue by fhollste** [jamesmfriedman/rmwc#424]
I updated to RMWC 5.1.8 from 3.0.10 and went through the changelog and fixed all breaking changes. However my app crashes on SSR: 
```
TypeError: base_1.classNames is not a function
    at Ripple.render (/node_modules/@rmwc/ripple/dist/index.js:177:38)
```
Specifically this line: https://github.com/jamesmfriedman/rmwc/blob/master/src/ripple/index.tsx#L210
Checking /node_modules/@rmwc/base/index.tsx there is a linter error:

> This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

My project does not use TypeScript.

**Comment by jamesmfriedman** [comment]
Hi @fhollste, some questions for you:

- You say this is breaking on SSR, what version of Node are you currently running?
- Have you tried following the warnings suggestion of turning on esModuleInterop?
- The actual problem is this line https://github.com/jamesmfriedman/rmwc/blob/master/src/base/index.tsx#L6
- The import / export is being done this way to work around a bunch of different compatibility issues with the many varieties of module handling
- you've obviously found one more! There are SSR tests around all of the components (which are passing) which is why I think this might be a node version issue OR this could be from an update to the classNames library itself. Specifically I'm eyeballing the latest change in the classNames library which specifically says it effects esmodule handling https://github.com/JedWatson/classnames/blob/master/HISTORY.md#v226--2018-06-08

**Comment by jamesmfriedman** [comment]
One more thing that would be helpful for troubleshooting. Can you see what version of classNames is actually installed on your system? `npm ls classnames`. Another potential issue is that the external classNames 2.2.6 actually fixes your issue, but your package.lock file has it set to 2.2.5. If this is the case, then removing your lock file (or updating your lockfile manually) might resolve this.

**Comment by fhollste** [comment]
Thanks for the quick reply! Resolving classnames to 2.2.6 (instead of 2.2.5) fixed the issue!

**Comment by jamesmfriedman** [comment]
Woot woot. Well, always happy to know the issue was somewhere else. i'll make go ahead and update the package in package.json anyways, although any fresh installs shouldn't hit this issue from here on out.
