### ISSUE TITLE
Cannot make individual ListItems non-interactive

### ISSUE THREAD

**Issue by robcaldecottvelo** [jamesmfriedman/rmwc#429]
**RMWC 5.1.8**

In RMWC4 you could selectively make a `ListItem` interactive by:

- Adding `nonInteractive` to the `List`
- Adding `ripple={true}` to items you wanted to be interactive

However, this behaviour has now changed. If you add `nonInteractive` to a `List` then all items will be static, regardless of their `ripple` prop. If you remove `nonInteractive` then even items with `ripple={false}` can be clicked and show a CSS ripple effect.

An example is here:

https://codesandbox.io/s/84qlmm91rj

Now, this may be by design, especially as `nonInteractive` is a `List` property and the MDC docs for the CSS class this represents say:

> ...disables interactivity affordances.

But it does mean the list is less customisable. For example, we want some items to be static as they represent data items that are still loading.

To workaround this we are using the `ListItem` `disabled` prop and using some CSS to ensure that text does not look disabled.

**Comment by jamesmfriedman** [comment]
Looking a bit deeper, this isn't something that can be fixed in RMWC. Really, whats happening appears to be the appropriate behavior.

If you look closer in your example, the listItem in the second list where ripple={false} actually does have the ripple disabled. What you're seeing is a hover effect put on there by the list.

A simple workaround is to just hide the before and after content via css. In this example I've added a className to the static item and updated the styles.css file.

https://codesandbox.io/s/q9ro98oy2j
