### ISSUE TITLE
Warning: findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by zemirco** [jamesmfriedman/rmwc#512]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

## RMWC or MDC?

RMWC

RMWC is a React wrapper for Google's official MDC that provides a props based interface for their components. Is the bug being caused by RMWC, or MDC? Please do your best to track down where the bug is originating from and post your issue to the proper repository. MDC bugs should be filed here https://github.com/material-components/material-components-web/issues.

Do you really want it fixed? Make a repro in the sandbox!
> - Javascript Sandbox https://codesandbox.io/s/kpy13vqnr
> - Typescript Sandbox https://codesandbox.io/s/kl0w4xp95

- What RMWC Version are you using [major.minor.patch]:

@rmwc/button: 5.7.0

- Name your build system [Webpack, Rollup...]:

Webpack

- Describe the bug with as much detail as possible:

We're using `React.StrictMode` in our application.

```tsx
  <React.StrictMode>
    <I18nProvider>
      <BrowserRouter>
        <Index />
      </BrowserRouter>
    </I18nProvider>
  </React.StrictMode>
```

Inside one of our components I used your button.

```tsx
        <Button
          name="foo"
          type="button"
          onClick={doFoo}
          outlined={true}
        >
          foo
        </Button>
```

- What happened, and what was supposed to happen:

In the command line I saw the following warning.

```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Ripple which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
    in button (created by Button)
    in Button (created by ForwardRef)
    in Ripple (created by ForwardRef)
    in ForwardRef (created by Context.Consumer)
    in withRipple(Button) (created by ScopeComponent)
    ...
    ...
```

`findDOMNode` is used here https://github.com/jamesmfriedman/rmwc/blob/0ac0e4c1576783e69648fe5ff15795bd6df27e8b/src/ripple/index.tsx#L127

We're coming from https://github.com/material-components/material-components-web-react and would like to start your wrapper. We really like what we see and we want to help / collaborate. Quite some time ago we wrote our own Material Design Implementation https://github.com/HBM/md-components but stopped when Google started building their own wrapper. We jumped on the bandwagon and hoped to find stability. Unfortunately we didn't find it.

Maybe you could push us into the right direction so we could create a PR. We're just getting started with your code base.

Best regards,
Mirco

**Comment by jamesmfriedman** [comment]
Hi @zemirco, welcome.

I readily accept PRs for any of this stuff. If you and your team want to take a more consistent role I can make you official contributors after we get through a few PRs.

I'm sorry to hear about what happened with mdc-react. The team was very friendly, I always feared the same thing happening which is why I kept RMWC alive and well.

In regards to this codebase, there are some guidelines in CONTRIBUTING.md which you can check out. The integration with the mdc library is a bit strange to say the least, the foundation adapter pattern is about as opposite as you can get from React as possible. One of the positives that came out of mdc-react I think is the core team felt some of the pain when eating the dogfood. All of this is just a headsup to say that the internals aren't always the most understandable thing at first glance.

In regards to this specific issue, I'm not exactly sure how to work around it. The trick with ripples is they don't have any DomNodes of their own, and they have to find the first available DomNode to apply logic to. The React component tree can be infinitely deep before it actually gets to one, including components from third parties (which makes ref forwarding / passing impractical).  

Here is a contrived example of the problem to solve.

```
<Ripple>
  <SomeComponent>
    <AnotherComponent>
      <TheComponentThatActuallyHasADomNode />
    <AnotherComponent/>
  </SomeComponent/>
</Ripple>
```

In a perfect world, you might think that Ripple could just wrap `<TheComponentThatActuallyHasADomNode />` but that would force it to accept a ref, and it also might have a sub tree of other react components and not have anywhere to pass it to.

So thats the short story of how I got to the implementation ^. I'd start in the ripple component 😎.

**Comment by Fa-So** [comment]
Hi Guys,
would this approach be helpful?
```tsx
export class Ripple extends FoundationComponent<
  MDCRippleFoundation,
  RippleProps
> {
  static shouldDebounce = true;
  static displayName = 'Ripple';

  private root = this.createElement('root');
  private surface = this.createElement('surface');
  private isTouched = false;
  private rippleRef = React.createRef<Element>(); //<- add
  .
  .
  .
  sync(props: RippleProps, prevProps: RippleProps) {
    this.root.setRef(this.rippleRef.current); // <-change

    if (props.unbounded !== prevProps.unbounded) {
      this.foundation.setUnbounded(!!props.unbounded);
    }
  }
```
🤔

**Comment by jamesmfriedman** [comment]
Per my previous comment, getting the ref is incredibly challenging for a component that’s supposed to work on anything and all other components, so I’m not sure how you intend on setting the ref to anything.

**Comment by jamesmfriedman** [comment]
I've looked into other ways of addressing this but I'm still at a loss.

The only way for the Ripple component to continue to work in all cases is to use this method. Any passing of refs leads to the same issue I described above. Is there anyway to disabled the warning / error in strict mode for this particular feature?

**Comment by Fa-So** [comment]
[Maybe the material-ui issues can help you](https://github.com/mui-org/material-ui/issues/13394)
