### ISSUE TITLE
Slider: thumb-fill desync

### ISSUE THREAD

**Issue by jsejcksn** [jamesmfriedman/rmwc#524]
- [CodeSandbox link](https://codesandbox.io/s/play-audio-file-v1joi?module=%2Fsrc%2Fcomponents%2FPlayer.js)
- **Screen recording:** https://imgur.com/a/rqxTPls (easter egg: audio)
- **RMWC version:** `5.7.0`

<details>
<summary>Software versions</summary>

- **Browser:** Chrome`78.0.3904.108`
- **OS:** macOS`10.15.1`
- **`npm` dependencies:**:  
```json
{
    "@emotion/core": "10.0.22",
    "@material/button": "4.0.0",
    "@material/icon-button": "4.0.0",
    "@material/ripple": "4.0.0",
    "@material/slider": "4.0.0",
    "@rmwc/button": "5.7.0",
    "@rmwc/icon-button": "5.7.0",
    "@rmwc/provider": "5.7.0",
    "@rmwc/ripple": "5.7.0",
    "@rmwc/slider": "5.7.0",
    "react": "16.12.0",
    "react-dom": "16.12.0",
    "react-scripts": "3.2.0"
  }
```
</details>

## Description:

When
 - using a Slider with a controlled value, and
 - updating the controlling state value independently by two functions:
   - an external function, and
   - the `onInput` prop

the slider thumb position does not sync with the fill position. It's possible this is due to my component code (this is the first time I'm using this library and that was a quick demo), but I think it's an actual bug—and I'm not sure where, exactly: I can't reproduce on mobile (iOS, Chrome). Can someone verify? Thanks!

**Comment by jamesmfriedman** [comment]
First of all, thank you for putting together such a comprehensive example. Your audio player is super cool. It does appear to be a real bug. For some reason, their are two 'translateX' values being applied to the thumb, one with the proper value and another that is stuck on translateX(50%) which appears to be winning. It's possible the issue is upstream with google, but I'll definitely look into this!

**Comment by jamesmfriedman** [comment]
Got it!

1) This is actually a browser specific bug, chrome only. Works fine in Safari and Firefox.
2) Seems to be caused by a but with will-change + transition making the element not repaint when it is supposed to
3) A simple solution which fixes the sync issue and doesn't appear to have any other issues for your use case is to just disable the transitions on the thumbContainer element completely with an !important css rule. https://codesandbox.io/s/play-audio-file-710nx
4) We need to file an issue with MDC, your reproduction is perfect for this.

**Comment by jsejcksn** [comment]
@jamesmfriedman I'm glad I could surface this! I added a button to toggle that css override fix in my original demo if you want to fork it again—it makes it easy to toggle between behaviors.

Two questions:

1. What does the `transition` actually do on the thumb? I didn't notice any visual differences.
2. Are you going to post the issue upstream or do you need something else from me?

**Comment by jamesmfriedman** [comment]
I think it's always helpful if the community can post the upstream issues and reference this one, otherwise the team at Google is going to get sick of me ;).

I believe the behavior was added by them so that the thumb gracefully slides if the value is programatically changed. For your case, you wouldn't notice because you're updating the position on every animation frame. But imagine the value was at zero and then it was set to 50 in the next frame, you'd want to see a smooth transition and not have the knob jump. Thats my best guess at least.

**Comment by jsejcksn** [comment]
@jamesmfriedman Ah, yes, I see the transition effect now—it's so fast, I didn't notice it before.

**Comment by jsejcksn** [comment]
@jamesmfriedman I think it might be better if you handle upstream issues. I've filed this three times now.

**Comment by jamesmfriedman** [comment]
Lol. Well the first one was the wrong repo. The second one is accurate, they’ll get around to it but at least you have a workaround for now.
