### ISSUE TITLE
feat: auto-select based on user typing

### ISSUE THREAD

**Issue by nicholaschiang** [jamesmfriedman/rmwc#610]
Not exactly sure if this is the right place to put this issue (feel free to forward it unto the MDC repository if this isn't the right place), but I thought here would be a good starting point.

The `Select` component should auto-select based on user input (this is already pretty common for most native browser `<select>` tags, but isn't yet officially supported by the [MDC Select](https://material.io/develop/web/components/input-controls/select-menus/) component). When the `Select` is focused, you should listen for `keydown` events and select the options that match the typed letters.

See [this issue](https://github.com/tutorbookapp/covid-tutoring/issues/19) for more information.

**Comment by jamesmfriedman** [comment]
Agreed, it should definitely work like the native select. I would recommend opening up, or upvoting an issue on the MDC side since it seems like it should be part of it.

I'm not kidding when I say the Select component has been rewritten on Google's side at least 4 times. I'm afraid for them to touch it as it has amounted to a large number of issues for this library :).

**Comment by sangdth** [comment]
I was trying to do [something similar](https://codesandbox.io/s/select-options-gr2sq), I hope the `Select` could do the heavy lifting for me :P
