### ISSUE TITLE
Documentation about foundationRef

### ISSUE THREAD

**Issue by sangdth** [jamesmfriedman/rmwc#612]
I'm not sure this is an issue or not, but I can't find a good information for using `foundationRef`. What are the use cases and best practices?

**Comment by jamesmfriedman** [comment]
I should probably add some docs around that.

Short answer, the best practice is to avoid using it at all costs. The foundation / adapter pattern is one Google came up with for this project and is fickle to say the least. Previous versions of this library inadvertently exposed the foundation because the components were using React Classes. Basically, someone would get a ref to the component, and then access the foundation that was stored on it. foundationRef was added with the V6 hooks release to provide an upgrade path for people that had been messing around with the internals. One of the reasons it's not documented is I really really don't want people to use it :) 

Now, reasons you might want to use it
- You're not afraid of other peoples src code and want to dig around to see what Google is doing
- There is some highly specific feature that you need that Google is offering from their components that RMWC is not currently providing.
- There is some highly specific bug that you need to monkey patch since it can take a while to get the fixes in from upstream. In this case, I'd rather open an issue and patch in here.

**Comment by sangdth** [comment]
Thanks for really useful comment.

I asked this because recently I'm working on a small issue related to `IconButton` focus. In our project we've created another DialogHeader to use it with RMWC Dialog. And for some weird reason I can not call `this.buttonRef.current.blur()` to clear the focus on that IconButton inside the header.

For now I work around with `<IconButton tabIndex={-1} ... />`, and I think this problem has nothing to do with `foundationRef`.

But still thanks for your awesome works and great support. I will close this issue.
