### ISSUE TITLE
Migration to v6 broke the SASS compilation

### ISSUE THREAD

**Issue by BenMoreton** [jamesmfriedman/rmwc#615]
- What RMWC Version are you using [major.minor.patch]:
I'm using RMWC 5.7.2, and the error occurs when trying to migrate to 6.x.x

- Name your build system [Webpack, Rollup...]:
Create React App, ejected but with default config (webpack etc.)

- Describe the bug with as much detail as possible:
When compiling sass, I have this error:

```
{
  "status": 1,
  "file": "node_modules/@material/button/mdc-button.scss",
  "line": 24,
  "column": 10,
  "message": "Invalid CSS after \"@include mixins\": expected 1 selector or at-rule, was \".core-styles;\"",
  "formatted": "Error: Invalid CSS after \"@include mixins\": expected 1 selector or at-rule, was \".core-styles;\"\n        on line 24 of node_modules/@material/button/mdc-button.scss\n        from line 2 of src/css/button.scss\n        from line 15 of src/css/all.scss\n>> @include mixins.core-styles;\n\n   ---------^\n"
}
```

In my .scss files, I use this as specified here in the doc, for example : 
```
@import "@material/button/mdc-button";
```
https://rmwc.io/styling-theming#sass-customization

- What happened, and what was supposed to happen:
Testing the app or building it is no longer working

Has the documentation not been updated since it worked in version 5.x.x?

**Comment by jamesmfriedman** [comment]
RMWC being upgraded also means that the Google Library thats being used internally also gets updated. All of the SASS handling is outside of the scope of this project so I don't see how this could be a problem here. 

The documentation has not been updated, but again it shouldn't have changed. Just based on your error it's coming from the @material library.

**Comment by BenMoreton** [comment]
Thanks for your answer.

Here's how to reproduce the error:
```
npx create-react-app my-app
npm i node-sass
```
Rename app.css to app.scss

`npm i rmwc@latest`

Adding @import "~@material/button/mdc-button"; to app.scss

`npm run start`



> The documentation has not been updated, but again it shouldn't have changed. Just based on your error it's coming from the @Material library.

It seems to have changed. Even if it's coming from the @Material library, Perhaps the documentation should be updated to indicate that SASS is no longer supported at this time.

**Comment by jamesmfriedman** [comment]
Hi Ben,

I'm not trying to be rude, but this is straight from the RMWC docs. Not sure how it could be stated any clearer.

> Additional customization can be done through your own SASS build. This is a feature of the material-components-web, not RMWC. There are several options to modify components such as mixins and component specific SASS variables. Please refer to the Material Web Components documentation for that specific component.

To say V6 broke SASS is incorrect. It has the same support as it always has, but if you want to use SASS you'll have to refer to the material docs.

Some things to help you troubleshoot
- I can say with almost complete certainty your issue is not caused by any code coming from this library
- Look at material-components-web changelog
- File an issue with material-components-web
- Chat material-components-web up on discord
- This could be an issue with create-react-apps sass rules
- Quick google search illuminates a lot of the reasons this can happen with your webpack config https://www.google.com/search?ei=7AGfXtuSMIy8tgWdiqigDg&q=webpack+invalid+CSS+after&oq=webpack+invalid+CSS+after&gs_lcp=CgZwc3ktYWIQAzIECAAQHjIECAAQHjoECAAQRzoGCAAQBxAeUJM-WMtLYI1NaABwAngAgAH4AYgBlQmSAQUwLjcuMZgBAKABAaoBB2d3cy13aXo&sclient=psy-ab&ved=0ahUKEwjbuP2Y3PnoAhUMnq0KHR0FCuQQ4dUDCAw&uact=5
