### ISSUE TITLE
Label of text area is displayed incorrectly in dialogs

### ISSUE THREAD

**Issue by fdc-viktor-luft** [jamesmfriedman/rmwc#680]
The problem occurs only if the text area contains a value AND is outlined AND inside of a dialog.
If you focus the text area once the problem vanishes.

You can find in the created sandbox a dialog button, which you need to push and inside the opened dialog, you should directly the mentioned problem.

Sandbox: https://codesandbox.io/s/rmwc-typescript-sandbox-sflq6?file=/src/index.tsx

**Comment by nicholaschiang** [comment]
I just opened a duplicate (#695). @jamesmfriedman could you take a look at this?

**Comment by EskiMojo14** [comment]
Experiencing the same issue within a dismissible drawer.
![image](https://user-images.githubusercontent.com/18308300/95687469-bc5f6f80-0bfb-11eb-8092-1af457793e4f.png)

**Comment by jmasukawa** [comment]
I'm also encountering this problem. As I understand it, the root cause comes from the [measure ref for the notched outline](https://github.com/jamesmfriedman/rmwc/blob/master/src/notched-outline/foundation.tsx#L20) setting the width for the notch when the DOM is in an "unstable" state.

In the case of a `Dialog` or `Drawer`, the "unstable" scenario occurs during transition / animation as the `Dialog` / `Drawer` is opening.

Here's a fork of the code sandbox from @fdc-viktor-luft, which has a modification to delay rendering the content until after the `Dialog` has fully opened. At this time, it's know the DOM is "stable", and the labels render correctly. https://codesandbox.io/s/rmwc-typescript-sandbox-forked-6nmjw?file=/src/index.tsx

That said...I'm not sure what an ideal solution would be.

One naive thought, is to re-trigger the measure ref to set the notched label correctly, when the underlying element changes from a bad state to a known good one. For example, a `useLayoutEffect` hook that sets the width again after `measureRef.current.getClientRects().length` changes.  In the case of a `Dialog` or `Drawer`, this will probably change from 0 (while the dialog is opening), to 1 (after it has fully opened and "DOM settles"). Though this is definitely a hacky / symptomatic approach for a fix, so I'm not necessarily advocating for this. I'm just trying to illustrate the nature of the problem a bit more. 🙂
